In [2]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [14]:
np.array([(2**a)/a for a in np.arange(1, 20)], dtype=np.double)

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [15]:
np.sum(np.array([0.1**(3*i)*0.2**(4*i) for i in np.arange(0, 5)], dtype=np.double))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

basic slice syntax is i:j:k where i is the starting index, j is the stopping index, and k is the step k != 0

In [5]:
matrix = np.zeros((8,8))
matrix[1::2,1::2]=1
matrix[::2,::2]=1
matrix

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [6]:
X = np.random.random((5, 2))

polar_radius = np.sqrt(X[:,0]**2 + X[:,1]**2)
X[:,1] = np.arcsin(X[:,1]/polar_radius)
X[:,0] = polar_radius
X

array([[0.56191343, 1.13331684],
       [0.84900101, 0.92266269],
       [0.60324829, 0.99470067],
       [0.94461961, 1.29594136],
       [0.9389497 , 0.35540417]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [7]:
X = np.random.random((10, 10))

x_max = np.argmax(np.max(X,axis = 0))
y_max = np.argmax(np.max(X,axis = 1))
                  
X[x_max,y_max]

0.5957286237784718

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [16]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))
dists = np.array([np.linalg.norm(X[i] - y) for i in range(0, X.shape[0])])
id_min = np.argmin(dists)
print(X[id_min])

[0.09247153 0.73119386]


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [17]:
@np.vectorize
def func(x):
    if x < 0: 
        return x ** 2 + 2 * x + 6
    elif x < 2:
        return x + 6
    else: 
        return x ** 2 + 4 * x - 4
func(np.arange(-3, 3.00001, 0.5))

array([ 9.  ,  7.25,  6.  ,  5.25,  5.  ,  5.25,  6.  ,  6.5 ,  7.  ,
        7.5 ,  8.  , 12.25, 17.  ])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [18]:
X = np.random.random((10, 10))

X = (X.T - np.mean(X, axis=1)).T
np.mean(X, axis=1)

array([-6.66133815e-17, -3.33066907e-17, -3.33066907e-17,  1.11022302e-17,
       -4.44089210e-17,  0.00000000e+00,  1.11022302e-17, -5.55111512e-17,
        4.44089210e-17, -3.33066907e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [20]:
X = np.random.normal(loc=5, scale=2., size=1000)
MX = np.mean(X)
DX = np.std(X) ** 2
print(MX)
print(DX)

4.994292560813814
3.861102462655286


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [22]:
def build(dim):
    matrix = np.arange(0, dim)
    for i in range(1, dim):
        tmp = np.hstack((np.arange(i, dim), np.arange(0, i)))
        matrix = np.vstack((matrix, tmp))
    return matrix

print(build(5))

[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]
